# Maximum version of php for silverstripe behat is currently 7.3
jobs:
  include:
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.7.x-dev"
        - REQUIRE_RECIPE_TESTING=^1
        - BEHAT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev"
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.8.x-dev"
        - REQUIRE_RECIPE_TESTING=^1
        - BEHAT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
