# Range is now just 2.x-dev - reason being the phpunit 9 requires framework 4.10, and there will not be a 2.10 release
jobs:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
        - PHPSTAN_TEST=1
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_TEST=1
        - COW_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
        - COMPOSER_INSTALL_ARG=--ignore-platform-reqs
