jobs:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.5.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
        - PHPSTAN_TEST=1
    - php: 7.2
      env:
        - DB=PGSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.6.x-dev"
        - PHPUNIT_TEST=1
        - COW_TEST=1
    - php: 7.3
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.7.x-dev"
        - PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.x-dev"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.x-dev"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3@dev || 4.x-dev"
        - COMPOSER_INSTALL_ARG=--ignore-platform-reqs
